// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MTG_App;
//
//    var cardRef = CardRef.FromJson(jsonString);

namespace MTG_App
{
    using System;
    using System.Collections.Generic;
    

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CardRef
    {
        [JsonProperty("cards")]
        public Dictionary<string, Card> Cards { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("multiverse_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long MultiverseId { get; set; }

        [JsonProperty("echo_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long EchoId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("expansion")]
        public string Expansion { get; set; }

        [JsonProperty("set_code")]
        public string SetCode { get; set; }
    }

    public partial class CardRef
    {
        public static CardRef FromJson(string json) => JsonConvert.DeserializeObject<CardRef>(json, MTG_App.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CardRef self) => JsonConvert.SerializeObject(self, MTG_App.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
